plugins {
    id 'java'
    id 'maven-publish'
}

group = 'net.nikdo53'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    repositories {
        maven {
            url = "$rootDir/build/maven"
        }
    }
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}



test {
    useJUnitPlatform()
}